### ISSUE TITLE
setup GH Page to domain name

### ISSUE THREAD

**Issue by Pongch** [bazaarfinance/bazaarfinance#23]
set up the GH Page to point to a domain name w/ an SSL cert

**Comment by jrhite** [comment]
custom url is working.

go to: thebazaar.finance

(https will be setup tomorrow, http only for now)

also try going to: bazaarfinance.github.io/bazaarfinance

it redirects correctly to thebazaar.finance.

will close when https is working too.

**Comment by jrhite** [comment]
https is working as well and updated for new frontend code!
